# Generated by Django 2.1.5 on 2019-01-15 18:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('code', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'randomuser',
            },
            managers=[
                ('objects_randomuser', django.db.models.manager.Manager()),
            ],
        ),
    ]
