# Generated by Django 2.1.5 on 2019-01-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomuser',
            name='mobile_number',
            field=models.CharField(max_length=25),
        ),
    ]
